2#! /bin/sh

xrdb ~/.Xresources

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
   for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
       # shellcheck source=/dev/null
       [ -x "$f" ] && . "$f"
   done
   unset f
fi

[[ -f ~/.xprofile ]] && . ~/.xprofile
[[ -f ~/.Xmodmap ]] && xmodmap ~/.Xmodmap

[[ -f ~/.screenlayout/layout.sh ]] && sh ~/.screenlayout/layout.sh

progs=("picom" "dunst" "dwmblocks" "nm-applet" "blueman-applet" "xfce4-power-manager")

for prog in ${progs[*]}; do
    pidof -sx $prog || $prog &
done >/dev/null 2>&1

feh --bg-fill ~/.wallpaper.jpg >/dev/null 2>&1

export XDG_SESSION_TYPE=x11
export XDG_CURRENT_DESKTOP=KDE
export XDG_SESSION_DESKTOP=KDE
export DESKTOP_SESSION=plasma
exec dwm
